### PR TITLE
fix: issue when back to home screen.

### LINKED ISSUE #97: iOS recording corrupted when going to background
Hi :wave:

We notices that when the app goes to the background during the recording, the MP4 gets corrupted (cannot be opened). 

I am aware that on iOS ReplayKit only allows you to record the app window, but technically it should keep recording the app in the background, no?

Do you have any idea what could be going on?

### PR DESCRIPTION
**Pull request by 345ml**
Add beginBackgroundTaskWithExpirationHandler.
For resolve #97

https://stackoverflow.com/questions/16353745/avassetwriter-fails-once-app-goes-in-background

### CODE REVIEW

**Comment by 345ml** [comment]
There may be a problem with this.
Let's say you made a 30-second recording and used 10 seconds of it for the home screen.

In this case,
Video is 30 seconds
Audio is 20 seconds
then I feel that the audio would be packed up front and the last 10 seconds would be silent.

**Comment by yutasuzuki** [comment]
@345ml Thanks.
Please wait a moment as I am unable to confirm this right now.
I understand about the audio issue.
I will try to gather more information after confirmation.

**Comment by 345ml** [comment]
@yutasuzuki 
Sorry late.
Thanks!

I noticed this problem after creating my pull request.
I have continued to investigate the issue, but have not yet come to an understanding of the problem.

**Comment by 345ml** [comment]
What I tried.

This way, we can determine if the app is in the background in startCaptureWithHandler.

That controls whether or not to run `appendSampleBuffer` and see if the result changes.
However, the desired result has not been obtained so far.

```Objective-C
[self.screenRecorder startCaptureWithHandler:^(CMSampleBufferRef sampleBuffer, RPSampleBufferType bufferType, NSError* error) {
    // Failure to do so will result in a memory error when accessing the sampleBuffer in the main thread.
    CFRetain(sampleBuffer);
    dispatch_async(dispatch_get_main_queue(), ^{
        if ([[UIApplication sharedApplication] applicationState] == UIApplicationStateBackground) {
        }
        
        CFRelease(sampleBuffer);
    });
}];
```

**Comment by 345ml** [comment]
I have fixed the problem with the time difference between audio and video in this commit.

https://github.com/yutasuzuki/react-native-record-screen/pull/104/commits/af69c4232e305c5e7a2d71b033b3027641ac4c32

This is accomplished by inserting silent audio.
I don't think this is a very pretty solution, but it seems to work well on my device.

**Comment by yutasuzuki** [comment]
@345ml Thanks!
However, I am sorry I have not yet been able to confirm this.

I would be fine with a tentative solution.

I have a question about the code.
Can you tell me why you moved `dispatch_get_main_queue()` into `granted` or `@available(iOS 11.0, *)`?

Is it an audio issue this time? Or another reason?

**Comment by 345ml** [comment]
@yutasuzuki 
Sorry for the lack of explanation regarding the code changes.

```Objective-c
[[UIApplication sharedApplication] applicationState]
```

Coming purple warning. `UIApplication applicationState must be used from main thread`

Take a look at the following sample.
In this pull request, you are now in case 2.

This can be changed to case 3.

I may not fully understand the relates between the `startCaptureWithHandler ` callback and whether it is running in the main thread.
If you are familiar with its, please let me know.

### Case 1. This code will coming a warning.
```Objective-c
dispatch_async(dispatch_get_main_queue(), ^{
  [self.screenRecorder startCaptureWithHandler:^(CMSampleBufferRef sampleBuffer, RPSampleBufferType bufferType, NSError* error) {
    [[UIApplication sharedApplication] applicationState]
  }];
});
```
### Case2 This code will no warning.
```Objective-c
[self.screenRecorder startCaptureWithHandler:^(CMSampleBufferRef sampleBuffer, RPSampleBufferType bufferType, NSError* error) {
  dispatch_async(dispatch_get_main_queue(), ^{
    [[UIApplication sharedApplication] applicationState]
  });
}];
```

### Case3 This code will no warning.
```Objective-c
dispatch_async(dispatch_get_main_queue(), ^{
  [self.screenRecorder startCaptureWithHandler:^(CMSampleBufferRef sampleBuffer, RPSampleBufferType bufferType, NSError* error) {
    dispatch_async(dispatch_get_main_queue(), ^{
      [[UIApplication sharedApplication] applicationState]
    });
  }];
});
```

**Comment by yutasuzuki** [comment]
@345ml Thanks! Understood!
I have not confirmed it yet, but I will merge it, please wait a moment.

**Comment by yutasuzuki** [comment]
@345ml 
Just merged your PR. And release v0.6.0!
Thanks!!

**Comment by 345ml** [comment]
@yutasuzuki 
Good job!

**Pull request merged**
