### PR TITLE
Update HBRecorder to v3.0.3

### PR DESCRIPTION
**Pull request by robrechtme**
Hi 👋 

This MR attempts to update HBRecorder to [v3.0.2](https://github.com/HBiSoft/HBRecorder/releases/tag/3.0.2) in order to fix https://github.com/yutasuzuki/react-native-record-screen/issues/117. I've also bumped the example to RN 0.73 using the [upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.72.0&to=0.73.6). I am still having some trouble getting this version to run correctly. I'm getting the following error and I can't seem to figure out what goes wrong 🤔 

```
android/src/main/java/com/recordscreen/RecordScreenModule.kt:14:12 Unresolved reference: hbisoft
```

### CODE REVIEW

**Comment by robrechtme** [comment]
Seems the issue is related to the library itself: https://github.com/HBiSoft/HBRecorder/issues/159

**Comment by robrechtme** [comment]
It is fixed in 3.0.3! So this is ready to be reviewed.

**Comment by yutasuzuki** [comment]
@robrechtme Thanks!
Did the React Native update have any impact on iOS?

**Comment by yutasuzuki** [comment]
@robrechtme 
I have confirmed that iOS works.
Thank you!!

**Pull request merged**
